# pandas
<center><img src="../images/stock/pexels-introspectivedsgn-4065800.jpg" width="500"></center>

pandas offers powerful data structures and manipulation tools that simplify data cleaning and analysis in Python. 

It's frequently used alongside NumPy for numerical operations, SciPy and statsmodels for statistical analysis, and Matplotlib for data visualization. 

pandas adopts NumPy's array-oriented computing paradigm, prioritizing array functions and avoiding explicit loops for data processing.

# Pandas Installation

You can install pandas with the following command:

```bash
!pip install pandas
```

However, just like with NumPy, I took the liberty of installing Pandas on the Jupyter Hub.

## Importing Pandas

We'll need to import pandas into your notebook/script before using it.

The standard convention for importing Pandas is as follows:

```python
import pandas as pd
```

Let's go ahead import pandas into our notebooks in the cell below:

In [7]:
# Import Pandas
import pandas as pd

# Pandas Data Structures
<center><img src="../images/stock/pexels-jeffrey-czum-254391-2346289.jpg" width="500"></center>
Pandas primarily uses two data structures:

* __Series__: 1-dimensional labeled array.
* __DataFrame__: 2-dimensional labeled table (collection of Series).

## Series

Think of a pandas Series as a single column of data with labels.

* __Default Labels__: By default, each item gets a number based on its position, just like in a Python list.
* __Custom Labels__: You can also give each item your own specific label (like a name or an ID). These labels can be numbers, text, or even combinations.
* __Data Types__: A Series can hold various types of data, but it's most efficient when all the items in a single Series are of the same type. This is important because, as we'll see later, Series become the columns in a DataFrame, and columns ideally have consistent data types.

__Series Illustration__

<center><img src="../images/illustrations/pandas-series-example.jpg"></center>

### Creating a Series from a List

We can easily create a pandas Series from a one-dimensional dataset, like a Python list, using the `pd.Series()` constructor.

For example, let's take this list and turn it into a Series:

In [8]:
# Data
popular_shows = [
    "Stranger Things",
    "The Mandalorian",
    "The Queen's Gambit",
    "Bridgerton",
    "Squid Game",
    "Succession",
    "Ted Lasso",
    "The Witcher",
    "Euphoria",
    "Ozark"
]

# Transform into a Series using pd.Series()
popular_shows_series = pd.Series(popular_shows)

# Output the Series
popular_shows_series

0       Stranger Things
1       The Mandalorian
2    The Queen's Gambit
3            Bridgerton
4            Squid Game
5            Succession
6             Ted Lasso
7           The Witcher
8              Euphoria
9                 Ozark
dtype: object

* Passing a list to `pd.Series()` creates a Series with automatic numeric labels (0, 1, 2, ...).
* The `.dtype` attribute tells us the data type of the elements within the Series.
* Text data (strings) are typically represented as the `object` dtype by default.

### Custom Labels

You can specify your own labels for the Series using the `index = sequence` argument within the `pd.Series()` function. For example:

In [9]:
# Data
popular_movies = [
    "Oppenheimer",
    "Barbie",
    "The Godfather",
    "Parasite",
    "Spirited Away"
]

# Transform into a Series with Custom Indices
indices = ["a", "b", "c", "d", "e"]

popular_movies_series = pd.Series(popular_movies, index = indices)

popular_movies_series

a      Oppenheimer
b           Barbie
c    The Godfather
d         Parasite
e    Spirited Away
dtype: object

Now, the Series uses the custom labels we provided instead of the default numbers.

### Accessing Data - Index Operator `[]`

Similar to Python lists, we can retrieve data from a Series using square brackets `[]` with the label or position.

For example: Which popular movie is associated with the label `d`?

In [10]:
# Access the element at label d
popular_movies_series["d"]

'Parasite'

### Accessing Data - `.loc` Accessor

Another way to access Series data by its label is using the `.loc` attribute. For example:

In [11]:
# Access the element at label d
popular_movies_series.loc["d"]

'Parasite'

### Accessing Data - `.iloc` Accessor

Even with custom labels, you can still access elements by their numerical position (like in a list) using the `.iloc` attribute. 

For example:

In [12]:
# Access the element at position 3
popular_movies_series.iloc[3]

'Parasite'

### Slicing Series Data

We can select multiple elements from a Series using slicing with the index operator `[]`, `.loc` (label-based slicing), and `.iloc` (position-based slicing). 

Here's how:

In [13]:
# Demonstrate [] slicing
popular_shows_series.iloc[:6]

0       Stranger Things
1       The Mandalorian
2    The Queen's Gambit
3            Bridgerton
4            Squid Game
5            Succession
dtype: object

In [14]:
# Demonstrate .loc slicing
popular_movies_series.loc["b":"c"]

b           Barbie
c    The Godfather
dtype: object

In [27]:
# Demonstrate .iloc slicing
popular_movies_series.iloc[0:2]

a    Oppenheimer
b         Barbie
dtype: object

## DataFrame

<center><img src="../images/stock/pexels-suki-lee-110686949-16200703.jpg" width="500"></center>

A pandas DataFrame is like a table with rows and columns. It's a 2D structure where each column can hold different types of data. Think of it as a collection of Series, all sharing the same row labels. Each column is essentially a Series.

__DataFrame Illustration__

<center><img src="../images/illustrations/pandas_dataframe_example.jpg"></center>

### Creating a DataFrame

##### `pd.DataFrame()`

We use the `pd.DataFrame()` function to create a pandas DataFrame.

In the code cell below, we will create a DataFrame from a given dictionary:

In [16]:
# Synthetic data
data = {
    'Name': ['TechGuru', 'FashionDiva', 'GameMaster', 'FoodieFun', 'TravelBug', 'MusicMania', 'BeautyQueen', 'DIYExpert', 'SportsFan', 'ComedyKing'],
    'Subscribers': [1500000, 2300000, 1800000, 1200000, 950000, 2700000, 1100000, 1600000, 2000000, 1400000],
    'Views': [120000000, 250000000, 180000000, 90000000, 60000000, 300000000, 80000000, 140000000, 220000000, 100000000],
    'Category': ['Tech', 'Fashion', 'Gaming', 'Food', 'Travel', 'Music', 'Beauty', 'DIY', 'Sports', 'Comedy'],
    'Country': ['USA', 'Canada', 'UK', 'USA', 'Australia', 'USA', 'USA', 'Canada', 'USA', 'UK'],
    'DateStarted': ['2021-01-01', '2020-05-15', '2019-11-01', '2022-03-10', '2018-09-20', '2023-02-01', '2021-07-01', '2020-10-01', '2019-04-01', '2022-01-01'] # Added DateStarted
}

# Create the DataFrame
youtube_df = pd.DataFrame(data)

# Output the DataFrame
youtube_df

          Name  Subscribers      Views Category    Country DateStarted
0     TechGuru      1500000  120000000     Tech        USA  2021-01-01
1  FashionDiva      2300000  250000000  Fashion     Canada  2020-05-15
2   GameMaster      1800000  180000000   Gaming         UK  2019-11-01
3    FoodieFun      1200000   90000000     Food        USA  2022-03-10
4    TravelBug       950000   60000000   Travel  Australia  2018-09-20
5   MusicMania      2700000  300000000    Music        USA  2023-02-01
6  BeautyQueen      1100000   80000000   Beauty        USA  2021-07-01
7    DIYExpert      1600000  140000000      DIY     Canada  2020-10-01
8    SportsFan      2000000  220000000   Sports        USA  2019-04-01
9   ComedyKing      1400000  100000000   Comedy         UK  2022-01-01

__Note:__

* Jupyter has a neat feature where if the last thing in a cell is a DataFrame, it'll display as an HTML table without needing `print()`, which gives you a cleaner look than the standard text output.

### Initial DataFrame Inspection

Pandas makes it easy to get a quick understanding of your DataFrame. We'll introduce four fundamental methods for this:

* `df.head()`: to see the beginning of your data.
* `df.tail()`: to see the end of your data.
* `df.describe()`: for a statistical summary of numerical columns.
* `df.info()`: to check data types and non-null values.

#### `df.head()`

The `df.head()` method returns the first five rows of the DataFrame.

In [17]:
# Demonstration
youtube_df.head(3)

          Name  Subscribers      Views Category Country DateStarted
0     TechGuru      1500000  120000000     Tech     USA  2021-01-01
1  FashionDiva      2300000  250000000  Fashion  Canada  2020-05-15
2   GameMaster      1800000  180000000   Gaming      UK  2019-11-01

#### `df.tail()`

The `df.tail()` method returns the last five rows of the DataFrame.

In [18]:
# Demonstration
youtube_df.tail(3)

         Name  Subscribers      Views Category Country DateStarted
7   DIYExpert      1600000  140000000      DIY  Canada  2020-10-01
8   SportsFan      2000000  220000000   Sports     USA  2019-04-01
9  ComedyKing      1400000  100000000   Comedy      UK  2022-01-01

#### `df.describe()`

The `df.describe()` method is a powerful tool for quickly understanding the distribution of your numerical data within a DataFrame. When called, it computes and summarizes several key statistical measures for each numerical column:

* __count__: The number of non-missing (non-NaN) values.
* __mean__: The average value.
* __std__: The standard deviation, a measure of the spread or dispersion of the data.
* __min__: The minimum value.
* __max__: The maximum value.
* __25% (Q1)__: The first quartile, meaning 25% of the data falls below this value.
* __50% (Median or Q2)__: The middle value; 50% of the data is below and 50% is above.
* __75% (Q3)__: The third quartile, meaning 75% of the data falls below this value.

This output provides a concise overview of the central tendency, dispersion, and shape of the numerical data in your DataFrame.

In [19]:
# Demonstration
youtube_df.describe()

        Subscribers         Views
count  1.000000e+01  1.000000e+01
mean   1.655000e+06  1.540000e+08
std    5.529969e+05  8.044322e+07
min    9.500000e+05  6.000000e+07
25%    1.250000e+06  9.250000e+07
50%    1.550000e+06  1.300000e+08
75%    1.950000e+06  2.100000e+08
max    2.700000e+06  3.000000e+08

### More DataFrame Creation Techniques

Beyond Python sequences, you can create Pandas DataFrames in several other ways:

* __From Series__: Combining one or more Series.
* __From Files__: Reading CSV, Excel, and other formats.
* __From APIs__: Retrieving data from web sources.

### Reading Data from Files
<center><img src="../images/stock/pexels-eva-bronzini-6068493.jpg" width="500"></center>
Pandas provides powerful and convenient functions to import data from various external file formats directly into DataFrames. This section will introduce you to these essential tools for bringing your data into the Pandas environment.

#### Reading CSV Files with pd.read_csv()

The `pd.read_csv()` function is your primary tool in Pandas for reading data stored in Comma Separated Values (CSV) files. This function is incredibly versatile and can handle a wide variety of CSV file structures. Let's explore its basic usage.

##### Reading CSV files from the Web
Pandas makes it incredibly convenient to read CSV files not only from your local computer but also directly from web URLs. This is particularly useful when working with publicly available datasets

Here is the general syntax:

```python
URL = "YOUR_CSV_FILE_URL_HERE"
df = pd.read_csv(URL)
```

Explanation:

1. We begin by importing the Pandas library as pd.
2. You will replace `"YOUR_CSV_FILE_URL_HERE"` with the specific web address of the CSV file you want to read. This URL is stored in a variable.
3. The `pd.read_csv(URL)` function is then called, which performs the following actions:
    1. __Fetches the data__: Pandas sends a request to the URL and retrieves the content of the CSV file.
    2. __Parses the data__: It interprets the comma-separated values and organizes them into a tabular structure.
    3. __Creates a DataFrame__: The parsed data is automatically loaded into a Pandas DataFrame, which we have named `df` in this example.
4. Once the data is in a DataFrame, you can use standard Pandas methods like `df.head()` to see the initial rows and `df.info()` to understand its structure (number of rows, columns, data types, and non-null values).

This method streamlines the process of working with online CSV datasets, allowing you to quickly load and begin analyzing data directly from the web.

#### Example: Reading Nike BikeTown Data from a URL
<center><img src="../images/generated/gemini_generated_panda_bike.jpeg" width="400"></center>
Now, let's put this into practice with some publicly available data from Nike BikeTown. We can directly read a CSV file containing trip data using the pd.read_csv() function and the file's web address.


Here's the URL for the BikeTown data:

```python
URL = "https://s3.amazonaws.com/biketown-tripdata-public/2018_05.csv"
```

For more BikeTown data, visit - [BikeTown - System Data](https://biketownpdx.com/system-data)

##### Importing and Inspecting the Data

Given the URL, let's do the following:

1. Read the BikeTown data from the provided URL into a DataFrame called `biketown_may`
2. Use the `.head()` method to display the first 5 rows of the DataFrame. What information do you think each column represents?

In [20]:
# Demonstration
URL = "https://s3.amazonaws.com/biketown-tripdata-public/2018_05.csv"
biketown_df = pd.read_csv(URL)

biketown_df

,RouteID,PaymentPlan,StartHub,StartLatitude,StartLongitude,StartDate,StartTime,EndHub,EndLatitude,EndLongitude,EndDate,EndTime,TripType,BikeID,BikeName,Distance_Miles,Duration,RentalAccessPath,MultipleRental
0,6624288,Subscriber,NW 13th at Marshall,45.530804,-122.684423,5/1/2018,0:06,NW 2nd at Everett,45.525367,-122.672546,5/1/2018,0:11,NaN,6503,0326 BIKETOWN,0.86,0:05:49,keypad,False
1,6624313,Subscriber,NW Johnson at Jamison Square,45.528637,-122.682019,5/1/2018,0:11,NaN,45.526398,-122.689363,5/1/2018,0:16,NaN,6162,0874 BIKETOWN,0.51,0:04:32,keypad_rfid_card,False
2,6624387,Subscriber,NW Marshall at Tanner Springs Park,45.530831,-122.681596,5/1/2018,0:24,NW Couch at 11th,45.523742,-122.681813,5/1/2018,0:27,NaN,6535,0817 BIKETOWN,0.75,0:03:28,keypad,False
3,6624410,Subscriber,NaN,45.516459,-122.630957,5/1/2018,0:28,NaN,45.516527,-122.622968,5/1/2018,0:30,NaN,6179,0503 BIKETOWN,0.35,0:02:29,keypad,False
4,6624448,Casual,NaN,45.529077,-122.654351,5/1/2018,0:36,NE 11th at Holladay Park,45.530279,-122.654669,5/1/2018,0:34,NaN,6548,0591 BIKETOWN,4.38,NaN,keypad,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79394,7269070,Subscriber,SW Naito at Ankeny Plaza,45.522696,-122.670349,5/31/2018,23:46,NE Wheeler at Multnomah,45.530867,-122.665889,5/31/2018,23:52,NaN,7242,0005 BIKETOWN,0.89,0:06:35,keypad_rfid_card,False
79395,7269071,Casual,SW 3rd at Ankeny,45.522479,-122.673297,5/31/2018,23:46,NaN,45.522924,-122.656663,6/1/2018,0:02,NaN,7104,0824 BIKETOWN,0.86,0:16:12,keypad,False
79396,7269072,Casual,SW Naito at Morrison,45.517826,-122.672496,5/31/2018,23:46,SW Naito at Morrison,45.517826,-122.672496,6/1/2018,0:34,NaN,6083,0468 BIKETOWN,3.08,0:47:36,keypad,False
79397,7269105,Casual,SW Naito at Ankeny Plaza,45.522696,-122.670349,5/31/2018,23:49,NaN,45.522924,-122.656663,6/1/2018,0:02,NaN,7287,0561 BIKETOWN,0.65,0:13:03,keypad,False
79398,7269113,Casual,NE Going at Grand,45.556454,-122.660379,5/31/2018,23:50,NE MLK at Knott,45.541800,-122.661485,6/1/2018,0:00,NaN,6655,0765 BIKETOWN,1.19,0:09:11,keypad,False

3. Use the `.info()` method to get a concise summary of the DataFrame, including data types and non-null values.

In [21]:
# Demonstration
biketown_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 79399 entries, 0 to 79398
Data columns (total 19 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   RouteID           79399 non-null  int64
 1   PaymentPlan       79399 non-null  object
 2   StartHub          53666 non-null  object
 3   StartLatitude     79377 non-null  float64
 4   StartLongitude    79377 non-null  float64
 5   StartDate         79399 non-null  object
 6   StartTime         79399 non-null  object
 7   EndHub            61560 non-null  object
 8   EndLatitude       79377 non-null  float64
 9   EndLongitude      79377 non-null  float64
 10  EndDate           79399 non-null  object
 11  EndTime           79399 non-null  object
 12  TripType          47 non-null     object
 13  BikeID            79399 non-null  int64
 14  BikeName          79399 non-null  object
 15  Distance_Miles    79399 non-null  float64
 16  Duration          78420 non-null  object
 17  RentalAccessPath  79399 non-null  object
 18  MultipleRental    79399 non-null  bool
dtypes: bool(1), float64(5), int64(2), object(11)
memory usage: 11.0+ MB

4. Use the `.shape` attribute to find the number of rows and columns in the DataFrame.

In [22]:
# Demonstration
biketown_df.shape

(79399, 19)

##### Selecting and Inspecting Columns

1. Select the `StartHub` column and display the first 10 unique values using the `.unique()` method. What are some of the starting bike station names?

2. Select the `Distance` column. Calculate and display the minimum and maximum values of the duration column using `.min()` and `.max()`.

In [23]:
# Demonstration
biketown_df["StartHub"].unique()

array(['NW 13th at Marshall', 'NW Johnson at Jamison Square',
       'NW Marshall at Tanner Springs Park', nan,
       'NE 11th at Holladay Park', 'NE Multnomah at 9th',
       'SW Yamhill at Director Park', 'SE Belmont at 33rd',
       'SE 29th at Belmont', 'SE Ladd at Hawthorne', 'SW 3rd at Ankeny',
       'NW Everett at 22nd', 'NW Naito at Ironside',
       'NW 18th at Flanders', 'SW 10th at Stark', 'NW 21st at Johnson',
       'SE 2nd Pl at Tilikum Way', 'NE Glisan at 24th',
       'NW Pettygrove at 15th', 'NW 19th at Johnson', 'NW Glisan at 21st',
       'NE 22nd at Burnside', 'N Mason at Williams', 'NW 23rd at Overton',
       'SE 29th at Hawthorne', 'SW River at Montgomery',
       'SW 18th at Jefferson', 'Tilikum West at SW Moody',
       'NE Alberta at 10th - Community Corral', 'SE 14th at Stark',
       'SW Salmon at Waterfront Park', 'SW Park at Portland Art Museum',
       'SW Moody at Aerial Tram Terminal', 'SW Morrison at 18th',
       'SW Harrison at 1st', 'SW 4th at College', 'NW Station at Irving',
       'SW Moody at Thomas', 'SW 10th at Columbia', 'NE 15th at Broadway',
       'NW 22nd at Lovejoy', 'NW 18th at Northrup',
       'NE 2nd at NE Schuyler',
       'N Killingsworth at Gay - Community Corral',
       'N Morris at Williams', 'N Williams at Fremont',
       'NE Holladay at MLK', 'SE 34th at Division',
       'N Killingsworth at Albina', 'SW Naito at Morrison',
       'N Mississippi at Beech', 'NW Kearney at 23rd',
       'SE Hawthorne at 20th', 'SE Belmont at 20th',
       'N Failing at Williams', 'NW Thurman at 24th',
       'NW 20th at Burnside', 'NE Fremont at 15th - Community Corral',
       'SE 29th at Stark', 'SW 12th at Clay',
       'SW Market at Keller Fountain Park',
       'N Interstate at Willamette - Community Corral',
       'NW Broadway at Everett', 'SE Clay at Water',
       'SE Elliott at Division', 'SW Morrison at Pioneer Courthouse Sq.',
       'SW 5th at Main', 'SW Park at W Burnside - Community Corral',
       'SE Clinton at 21st', 'NE 28th at Couch - Community Corral',
       'N Prescott at Interstate', 'SW 3rd at Morrison',
       'N Vancouver at Alberta', 'NW Couch at 2nd',
       'SE 34th at Hawthorne', 'SE Clinton at 26th', 'NE MLK at Knott',
       'NE Couch at MLK', 'NE Alberta at 24th - Community Corral',
       'N Mississippi at N Skidmore', 'NW Couch at 11th',
       'NW Raleigh at 21st', 'NE Alberta at 14th - Community Corral',
       'SE Water at Taylor', 'NE Wheeler at Multnomah',
       'SW Stark at Burnside', 'NW 11th at The Fields',
       'NW 10th at Everett', 'SW 2nd at Pine',
       'SW Broadway at Smith Memorial Student Union',
       'Metro Campus - Community Corral', 'NE Sandy at 16th',
       'SW 5th at Oak', 'SW Naito at Ankeny Plaza', 'SW 5th at Morrison',
       'SE 7th at Burnside', 'SE Gideon at 12th Ave MAX station',
       'SE 9th at Belmont', 'NW 2nd at Everett', 'NE Broadway at 12th',
       'SE Alder at 6th', 'Urban Center Plaza at SW 6th St',
       'SW Park at SW Wright (Oregon Holocaust Memorial) Community Corral',
       'NE Multnomah at Grand', 'SE 40th at Hawthorne',
       'SE 28th at Pine - Community Corral',
       'NE Alberta at 22nd - Community Corral', 'NW Flanders at 14th',
       'SW 4th at Jefferson (City Hall)', 'NW Front at 17th',
       'SE 30th at Division', 'NE Going at Grand', 'SE Belmont at 42nd ',
       'N Michigan at Killingsworth - Community Corral',
       'NE 17th at Killingsworth - Community Corral',
       'NE 33rd at Emerson - Community Corral',
       'NE 14th Pl at Prescott - Community Corral',
       'NE Killingsworth at 30th - Community Corral',
       'NE 33rd at Jarrett (Kennedy School) - Community Corral',
       'NE Alberta at 17th - Community Corral',
       'SE Taylor at Chavez Community Corral',
       'N Russell at Interstate Community Corral',
       'NE Alberta at NE 29th/30th - Community Corral',
       'N Concord at Killingsworth - Community Corral',
       'Rose Festival - Yamhill Entrance',
       'Rose Festival - Pine Entrance'], dtype=object)

##### Descriptive Statistics

* Use the `describe()` method on the `Distance_Miles` column to get summary statistics like mean, standard deviation, min, max, and quartiles.

In [24]:
# Demonstration

biketown_df["Distance_Miles"].describe()

count    79399.000000
mean         2.068690
std         18.721801
min          0.000000
25%          0.760000
50%          1.440000
75%          2.720000
max       5251.590000
Name: Distance_Miles, dtype: float64

##### Value Counts

* Find the top 5 most frequent starting stations using the `.value_counts()` method on the `StartHub` column.
* Find the number of unique `BikeID` values in the DataFrame using `.nunique()`. This tells you how many individual bikes were used in May 2020.
* Examine the `PaymentPlan` column using `.value_counts()`. What are the different payment plans and their counts?

In [25]:
# Demonstration
biketown_df["BikeID"].nunique()

996

In [26]:
biketown_df["PaymentPlan"].value_counts()

PaymentPlan
Casual        59207
Subscriber    20192
Name: count, dtype: int64

#### Beyond CSV: Other File Reading Methods

Pandas also provides functions for reading other common file types:

* `pd.read_excel()`: For reading data from Excel files (.xlsx, .xls).
* `pd.read_json()`: For reading data from JSON (JavaScript Object Notation) files.
* `pd.read_table()`: For reading delimited text files (similar to CSV but with customizable delimiters).
* `pd.read_parquet()`: For reading data from Parquet files, a columnar storage format.
* `pd.read_pickle()`: For reading serialized Python objects.
* `pd.read_sql()`: For reading data from SQL databases.

## Conclusion

Throughout this session, you've gained a foundational understanding of:

* __Pandas:__ Your go to library for data manipulation and analysis in Python.
* __DataFrames:__ The primary data structure in Pandas for handling tabular data
* __Series:__ The one-dimensional building block of DataFrames
* __Loading Data:__ Importing external datasets into your Jupyter Notebook
* __Initial Data Exploration:__ Methods like `.head()`, `.info()`, and `.describe()` are now tools you are ready to use for quickly understanding your datasets.

By now, you should feel comfortable loading a dataset and performing a quick initial assessment to get a feel for its contents.