## This should be a markdown section

In [ ]:
print("Hello")

Hello

# Another Markdown Section

In [ ]:
import pandas as pd
import json

songs_df = pd.read_json("vocaloid_setlist_songs.json")
songs_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2274 entries, 0 to 2273
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   title              2274 non-null   str
 1   english_title      2274 non-null   str
 2   artist             2274 non-null   str
 3   length_seconds     2274 non-null   int64
 4   setlist_frequency  2274 non-null   int64
 5   avg_setlist_order  2274 non-null   float64
 6   song_type          2274 non-null   str
 7   pv_services        2274 non-null   str
 8   times_favorited    2274 non-null   int64
 9   rating             2274 non-null   int64
dtypes: float64(1), int64(4), str(5)
memory usage: 177.8 KB

In [ ]:
songs_df.describe()

,length_seconds,setlist_frequency,avg_setlist_order,times_favorited,rating
count,2274.000000,2274.000000,2274.000000,2274.000000,2274.000000
mean,221.119173,2.375110,14.552881,27.866755,152.606860
std,93.778410,4.140145,12.440373,54.097615,273.224306
min,0.000000,1.000000,1.000000,0.000000,0.000000
25%,196.000000,1.000000,6.250000,1.000000,9.000000
50%,227.000000,1.000000,11.750000,6.000000,39.000000
75%,260.000000,2.000000,18.500000,27.750000,165.000000
max,2304.000000,75.000000,93.000000,648.000000,2985.000000

In [ ]:
songs_df.head(10)

,title,english_title,artist,length_seconds,setlist_frequency,avg_setlist_order,song_type,pv_services,times_favorited,rating
0,STARLIGHT,None,失いP feat. 花隈千冬,0,1,1.0,Cover,Nothing,0,0
1,Love is in Trouble -恋愛主義バージョン-,None,失いP feat. 弦巻マキ AI (Japanese),236,1,2.0,Cover,Youtube,3,13
2,HEADSTRONG -恋愛主義バージョン-,HEADSTRONG -Renai Shugi Version--,失いP feat. 京町セイカ AI,241,1,3.0,Cover,Youtube,1,5
3,精神疾患 -恋愛主義バージョン-,Mental Illness -Love Doctrine Version-,失いP feat. 夏色花梨,248,1,4.0,Cover,Youtube,4,14
4,愛をつかむ -恋愛主義バージョン-,Ai wo Tsukamu -Renai Shugi Version-,失いP feat. 小春六花 AI,311,1,5.0,Cover,Youtube,4,14
5,物語の始まり,Monogatari no Hajimari,失いP feat. 花隈千冬,0,1,6.0,Cover,Nothing,0,0
6,CAFETERIA -恋愛主義バージョン-,None,失いP feat. ついなちゃん AI,261,1,7.0,Cover,Youtube,3,11
7,My Lover -恋愛主義バージョン-,My Lover -Renai Shugi Version-,失いP feat. 桜乃そら SV,308,1,8.0,Cover,Youtube,3,11
8,許してください -恋愛主義バージョン-,Yurushite Kudasai -Renai Shugi Version-,失いP feat. 花隈千冬,181,1,9.0,Cover,Youtube,3,11
9,ビーチストーリー,Beach Story,失いP feat. 京町セイカ AI,0,1,10.0,Cover,Nothing,0,0

In [ ]:
mask = songs_df["setlist_frequency"] > 20

frequent_songs = songs_df[songs_df["setlist_frequency"] > 30]
frequent_songs

,title,english_title,artist,length_seconds,setlist_frequency,avg_setlist_order,song_type,pv_services,times_favorited,rating
64,千本桜,A Thousand Cherry Blossoms,黒うさP feat. 初音ミク,246,37,14.270270,Original,"NicoNicoDouga, Youtube",388,1858
73,ルカルカ★ナイトフィーバー,Luka Luka★Night Fever,samfree feat. 巡音ルカ,239,39,16.307692,Original,"NicoNicoDouga, Youtube",261,1329
83,メルト,Melt,ryo feat. 初音ミク,256,41,24.292683,Original,"NicoNicoDouga, Youtube, SoundCloud",297,1522
149,リモコン,Remote Control,"じーざすP, WONDERFUL★OPPORTUNITY! feat. 鏡音リン, 鏡音レン",312,31,14.419355,Original,"NicoNicoDouga, Youtube",206,1086
152,ワールドイズマイン,World is Mine,"ryo, supercell feat. 初音ミク",255,62,13.500000,Original,"NicoNicoDouga, Youtube",303,1609
188,???,None,,0,75,19.946667,Other,Nothing,2,12
268,Tell Your World,None,kz feat. 初音ミク,257,66,19.045455,Remix,Youtube,218,1226

In [ ]:
songs_df.sort_values(by="rating", ascending=False).head(10)

,title,english_title,artist,length_seconds,setlist_frequency,avg_setlist_order,song_type,pv_services,times_favorited,rating
123,ローリンガール,Rollin' Girl,wowaka feat. 初音ミク,196,22,12.318182,Original,"NicoNicoDouga, Youtube, SoundCloud",648,2985
96,炉心融解,Meltdown,iroha(sasaki) feat. 鏡音リン,333,15,11.800000,Original,"NicoNicoDouga, Youtube, SoundCloud, Bilibili",610,2770
1412,マトリョシカ,Matryoshka,"ハチ feat. 初音ミク, GUMI",201,6,13.333333,Original,"NicoNicoDouga, Youtube",487,2305
97,ロストワンの号哭,Lost One's Weeping,Neru feat. 鏡音リン Append (Power),217,8,14.750000,Original,"NicoNicoDouga, Youtube",419,2029
74,ワールズエンド・ダンスホール,World's End Dancehall,"wowaka feat. 初音ミク, 巡音ルカ",218,22,11.227273,Original,"NicoNicoDouga, Youtube",403,1911
64,千本桜,A Thousand Cherry Blossoms,黒うさP feat. 初音ミク,246,37,14.270270,Original,"NicoNicoDouga, Youtube",388,1858
945,恋は戦争,Koi wa Sensou,"ryo, supercell feat. 初音ミク",235,5,12.600000,Original,"NicoNicoDouga, Youtube",339,1785
80,ロミオとシンデレラ,Romeo and Cinderella,doriko feat. 初音ミク,280,29,14.137931,Original,"NicoNicoDouga, Youtube, Bilibili",331,1676
370,ヒビカセ,Resonate,Giga feat. 初音ミク V3 (Solid),250,16,8.875000,Original,"NicoNicoDouga, Youtube, SoundCloud, Bilibili",316,1662
152,ワールドイズマイン,World is Mine,"ryo, supercell feat. 初音ミク",255,62,13.500000,Original,"NicoNicoDouga, Youtube",303,1609

In [ ]:
songs_df.sort_values(by = "length_seconds", ascending=True).head(10)

,title,english_title,artist,length_seconds,setlist_frequency,avg_setlist_order,song_type,pv_services,times_favorited,rating
0,STARLIGHT,None,失いP feat. 花隈千冬,0,1,1.0,Cover,Nothing,0,0
5,物語の始まり,Monogatari no Hajimari,失いP feat. 花隈千冬,0,1,6.0,Cover,Nothing,0,0
9,ビーチストーリー,Beach Story,失いP feat. 京町セイカ AI,0,1,10.0,Cover,Nothing,0,0
10,黒いメガネ,Kuroi Megane,失いP feat. 花隈千冬,0,1,11.0,Cover,Nothing,0,0
11,僕の命,Boku no Inochi,失いP feat. 桜乃そら SV,0,1,12.0,Cover,Nothing,0,0
12,うさぎ小さいを食べたい,Usagi Chisai o Tabetai,失いP feat. 夏色花梨,0,1,13.0,Cover,Nothing,0,0
13,前を向いて,None,失いP feat. 夏色花梨,0,1,14.0,Original,Nothing,0,0
1886,歌うPower,None,なヲタ feat. 琴葉茜・葵,0,1,8.0,Original,Nothing,0,0
1932,さくらんぼ,Sakuranbo,"なヲタ feat. さとうささら (CeVIO AI), すずきつづみ (CeVIO AI)",0,1,1.0,Cover,Nothing,0,0
1863,ずんだもんと東北三姉妹のカレーうどん狂騒曲,Zundamon to Touhoku San Shimai no Curry Udon K...,南ノ南 feat. various,0,1,16.0,Cover,Nothing,0,0

In [ ]:
songs_df_clean = songs_df.query("length_seconds != 0")
songs_df_clean.sort_values(by="length_seconds", ascending = True).head(10)

<class 'pandas.DataFrame'>
Index: 2143 entries, 1 to 2273
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   title              2143 non-null   str
 1   english_title      2143 non-null   str
 2   artist             2143 non-null   str
 3   length_seconds     2143 non-null   int64
 4   setlist_frequency  2143 non-null   int64
 5   avg_setlist_order  2143 non-null   float64
 6   song_type          2143 non-null   str
 7   pv_services        2143 non-null   str
 8   times_favorited    2143 non-null   int64
 9   rating             2143 non-null   int64
dtypes: float64(1), int64(4), str(5)
memory usage: 184.2 KB

In [ ]:
songs_df_clean = songs_df_clean.query("pv_services != 'Nothing'")
songs_df_clean.sort_values(by="rating", ascending=True).head(10)

<class 'pandas.DataFrame'>
Index: 2090 entries, 1 to 2273
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   title              2090 non-null   str
 1   english_title      2090 non-null   str
 2   artist             2090 non-null   str
 3   length_seconds     2090 non-null   int64
 4   setlist_frequency  2090 non-null   int64
 5   avg_setlist_order  2090 non-null   float64
 6   song_type          2090 non-null   str
 7   pv_services        2090 non-null   str
 8   times_favorited    2090 non-null   int64
 9   rating             2090 non-null   int64
dtypes: float64(1), int64(4), str(5)
memory usage: 179.6 KB

In [ ]:
songs_df_clean = songs_df_clean.query("avg_setlist_order < 1000")
songs_df_clean = songs_df_clean.query("setlist_frequency > 5")
songs_df_clean.sort_values(by="avg_setlist_order", ascending=True)
songs_df_clean.info()

<class 'pandas.DataFrame'>
Index: 184 entries, 55 to 1412
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   title              184 non-null    str
 1   english_title      184 non-null    str
 2   artist             184 non-null    str
 3   length_seconds     184 non-null    int64
 4   setlist_frequency  184 non-null    int64
 5   avg_setlist_order  184 non-null    float64
 6   song_type          184 non-null    str
 7   pv_services        184 non-null    str
 8   times_favorited    184 non-null    int64
 9   rating             184 non-null    int64
dtypes: float64(1), int64(4), str(5)
memory usage: 15.8 KB